### ISSUE TITLE
Docker Hub alternative

### ISSUE THREAD

**Issue by tananaev** [traccar/traccar-docker#107]
@magna-z, looks like Docker is removing a free team option for Docker Hub. Is there a way to migrate to a non-team free account? I can probably create a repo as a personal account, right? What are the implications?

**Comment by tananaev** [comment]
Hacker News thread about this:

https://news.ycombinator.com/item?id=35166317

Hopefully they change their decision.

**Comment by tananaev** [comment]
Looks like there are some news from Docker:

https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/

I already submitted a support ticket to migrate to a personal account. We'll see how it goes.

**Comment by terrytw** [comment]
May I suggest setting up a alternative registry on github using ghcr.io?
