### ISSUE TITLE
Cant get traccar.xml

### ISSUE THREAD

**Issue by Larson-Sei180LX** [traccar/traccar-docker#112]
Hallo alle zusammen,

wenn ich hier nach der Anleitung den Docker-Container installiere, bekomme ich keine traccar.xml gedwonloaded. Zwar funktioniert traccar und läuft im WebUi, allerdings habe ich keine xml um Einstellungen vorzunehmen. Ich möchte auf meine Mariadb Datenbank umstellen und Telegram aktivieren, nur leider bekomme ich es einfach nicht zum Laufen. Kann mir jemand starthilfe geben?

**Comment by tananaev** [comment]
For questions please use the forum. Also ideally ask in English to include most people.

**Comment by mbirth** [comment]
Just for the record, the default `traccar.xml` is here:

https://github.com/traccar/traccar/blob/master/setup/traccar.xml
