### ISSUE TITLE
version 5.8

### ISSUE THREAD

**Issue by cserem** [traccar/traccar-docker#115]
Hello!

I have updated my existing traccar/traccar:5.7 setup (install steps taken from the readme.md)  to traccar/traccar:5.8 (re-created the container with the existing settings, just changed the image name)

I belive the upgrade executed properly:
In the logs I saw one SQL changeset execute, and on the webpage: ```Settings>Preferences >Server Version```>  shows 5.8

But the ```App Version``` is still on 5.7 (I tried disabling browser caching and reloading, but still no change)

Are there any additional steps to upgrade the App version, or 5.8 is simply not shipped in this relase?

Thanks
m

**Comment by tananaev** [comment]
Make sure you clear all the browser data for the website. Disabling network caching won't be enough.

In the future please ask questions on the forum instead.
