### ISSUE TITLE
MariaDB 11.0.2 connection error - Got an error reading communication packets

### ISSUE THREAD

**Issue by spencerandhill** [traccar/traccar-docker#116]
After upgrading my MariaDB to 11.0.2 I cannot start the traccar docker container. The Log of traccar show's:

![grafik](https://github.com/traccar/traccar-docker/assets/9363597/2a848164-65ad-47c8-bf4a-ebe9ca4fe53a)

And the MariaDB-Log is showing:
`2023-07-10 21:52:21 121 [Warning] Aborted connection 121 to db: 'traccar' user: 'traccar' host: '172.17.0.1' (Got an error reading communication packets)`

I've checked my setup of the traccar.xml for mariadb according to: https://www.traccar.org/mysql/ but it still keep's showing errors.

![grafik](https://github.com/traccar/traccar-docker/assets/9363597/332050fd-766b-4aca-9ca5-b403f67443f7)

EDIT:

- I'm using this on unraid 6.12.2
- I don't think it's a database issue, because the other containers using this mariadb-instance do still work
- I've set the Max Allowed Packet-Size to 256M:

`max_allowed_packet=256M`

**Comment by tananaev** [comment]
https://www.traccar.org/forums/topic/problems-in-docker-installation-with-mariadb-1102/

**Comment by spencerandhill** [comment]
Hi @tananaev 
the mentioned post in the forum doesn't tell any information, if the issue will be fixed soon, or if everyone has to fix and build their own version of traccar.

As I am using docker in an unraid environment, I cannot build traccar on my own.

-> Will there be a fixed version of traccar?

Best

**Comment by tananaev** [comment]
There will be at some point.
