### ISSUE TITLE
Container with the preview version to solve the MariaDB 11 problem

### ISSUE THREAD

**Issue by andreapx** [traccar/traccar-docker#118]
@magna-z Hi!
About the problem with MariaDB 11, since there are quite some people with it ([forum discussion](https://www.traccar.org/forums/topic/problems-in-docker-installation-with-mariadb-1102/page/2/#post-88446)), would you be so gentle to release a container with the preview version?
Thanks!

**Comment by andreapx** [comment]
@magna-z pleeeeeease!

**Comment by magna-z** [comment]
Can try new 5.9 version

**Comment by andreapx** [comment]
> Can try new 5.9 version

IT WORKS! Thanks a lot!!!!
