### ISSUE TITLE
Update Docker image to OpenJDK 17

### ISSUE THREAD

**Issue by mbirth** [traccar/traccar-docker#125]
Please update the Docker image to OpenJDK 17 - it's available from the AlpineLinux repo, so changing the `11` to a `17` in [Dockerfile.alpine](https://github.com/traccar/traccar-docker/blob/f1f955c65e137bd5b03664ef25f5e4ce344a29f8/Dockerfile.alpine#L8) should be sufficient.

**Comment by tananaev** [comment]
@magna-z we have to upgrade with Traccar 6.3. It's now the minimum version.

**Comment by magna-z** [comment]
@mbirth, try latest builds, please
