### ISSUE TITLE
GUI failed login requests not being logged

### ISSUE THREAD

**Issue by ptzenos** [traccar/traccar-docker#126]
Using traccar:latest (5.12-Alpine). Trying to set up fail2ban for the web interface.

While trying different combinations of username/passwords on the gui (port 8082) no failed login entries are being generated in the logs. The log level is set to "info" but I did try to also set it to "all". 

According to what I've found by searching around, it should log something like "INFO: login failed.* <HOST>".

Does this have something to do with the dockerized version or should I investigate something else?

Thanks

**Comment by tananaev** [comment]
You should investigate something else. Docker version is the same as the normal Traccar.
