### ISSUE TITLE
Java Runtime mismatch

### ISSUE THREAD

**Issue by juanitoddd** [traccar/traccar-docker#133]
Hello dear Friends,

I was trying to run the latest image of traccar, and got this error message 

`java.lang.UnsupportedClassVersionError: org/traccar/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

Can someone point me out how to overcome this issue ?
Many thanks in advance

**Comment by alexvannier-nc** [comment]
Hi, right now, you have to run the traccar version 6.2  "traccar:6.2" and do not use "traccar:latest" 
Traccar 6.3 is not yet ready. A modification on this repo has been pushed 1 hour ago. 
For more information : https://github.com/traccar/traccar-docker/pull/132#pullrequestreview-2214120755

**Comment by tananaev** [comment]
cc @magna-z

**Comment by magna-z** [comment]
Try new builds, please

**Comment by juanitoddd** [comment]
Many thanks ! doing `docker pull traccar/traccar:latest` solved the issue 👍
