### ISSUE TITLE
Is there a way to get into the apps folder?

### ISSUE THREAD

**Issue by ioiofadhil** [traccar/traccar-docker#139]
Hi, thank u for the lib. It's so helpful to build traccar app via docker! But i'm wondering.. How do we get into the apps folder? I'm trying to access the media folder that traccar provide (reference: https://www.traccar.org/forums/topic/video-dashcam-gps). But when i do:

```
docker exec -it <container-id> bash
```

the docker returns:
```
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
```

How to exactly access the app folders? Thank u!

**Comment by magna-z** [comment]
Use
```
docker exec -it <container-id> sh
```

**Comment by ioiofadhil** [comment]
> Use
> 
> ```
> docker exec -it <container-id> sh
> ```

Thanks!!
