### ISSUE TITLE
Is there a possibility to dockerize the Traccar Client?

### ISSUE THREAD

**Issue by Jkrox** [traccar/traccar-docker#141]
Hi,

Docker for me it's the best way to setup everything for production in my opinion. I was checking if there is a Docker image for [Traccar-Client](https://github.com/traccar/traccar-web) in order to deploy everything in a single `docker-compose.yml` with the database. I'm using https://github.com/traccar/traccar-docker/issues/101#issuecomment-2121524721 and it just works awesome.

I'm new implementing solutions with Traccar, so I want to make sure if this was already done by somebody else, if not, I can contribute doing it, as well as, making a dev container to develop and adjust anything the user wants, but mostly important, an image prepared for production.

**Comment by tananaev** [comment]
Sounds like you're talking about the web app, not Traccar Client. Very confusing.

The web app is already included in the single docker image that we have.

**Comment by Jkrox** [comment]
I meant the web app (Traccar Client because of client side), I have the problem that the image contains the app transpiled by [Babel](https://github.com/traccar/traccar-web/blob/2154ff10c729d6f1320798aaf0c2f78d603481f6/package-lock.json#L121-L141).

I know it's for better optimization and ready to be deployed, however If I want to adjust or change anything before deployment (dev purposes), it's not possible. So, my take here would be, instead of using a [zip file](https://github.com/traccar/traccar/releases) backend and frontend inside at once on a single image, we might dockerize the web app and the backend separately. Perhaps, implement the script that you use to transpile the code into the instructions once the user has done any adjustment or change, and finally, do the image for deployment.

https://github.com/traccar/traccar-docker/blob/57c7f32e14fdda9d1d0402702e631df3d54a1bd1/Dockerfile.alpine#L11

**Comment by tananaev** [comment]
How is it going to help with customization?

**Comment by Jkrox** [comment]
One of my customers pisses me off trying to change some styles stuff in the web app to make it look more according to his brand, and deploy it with a reverse proxy.

**Comment by tananaev** [comment]
I don't think it answers my question.

**Comment by Jkrox** [comment]
It is self-explanatory, you can't change anything with a transpiled code inside the image. 

It's going to help with the fact that you can adjust anything, add more parameters (env files, port binding, and so on) to the image, and make it more flexible. [Dev containers](https://code.visualstudio.com/docs/devcontainers/containers) might be a solution.

**Comment by tananaev** [comment]
It's not self explanatory to me. How is dividing one container into two solves the problem? Dev containers is a completely different purpose. It's for development, not deployment, so this would be the wrong repo for that.

**Comment by Jkrox** [comment]
Hi,

Yes, it was for development, however, I could solve the issue for myself. And yes, this was the wrong repo.

Regards.
