### ISSUE TITLE
How to mount the DB to an external folder?

### ISSUE THREAD

**Issue by ovizii** [traccar/traccar-docker#19]
I found these apparently old instructions: https://www.traccar.org/docker/ and tried adding 
`-v /my-database-folder:/opt/traccar/data/database` to your instructions but no entry appears inside /my-database-folder 

Please give me a hint how to make my DB survive inside a folder of my choice.

**Comment by magna-z** [comment]
Hello.
Yes, actual docs on [hub.docker.com](https://hub.docker.com/r/traccar/traccar/).
In you case, with using "H2 Database Engine", using something like:
```
$ docker run \
 -d --restart always \
 --name traccar \
 --hostname traccar \
 -p 80:8082 \
 -p 5000-5150:5000-5150 \
 -p 5000-5150:5000-5150/udp \
 -v /etc/timezone:/etc/timezone:ro \
 -v /etc/localtime:/etc/localtime:ro \
 -v /var/docker/data:/opt/traccar/data:rw \
 -v /var/docker/traccar/logs:/opt/traccar/logs:rw \
 -v /var/docker/traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro \
traccar/traccar:latest

$ ls -l /var/docker/data/
total 184
-rw-r--r--. 1 root root 176128 Aug 21 19:57 database.mv.db
-rw-r--r--. 1 root root    188 Aug 21 19:57 database.trace.db
```

**Comment by ovizii** [comment]
Thanks! that ":rw" at the end and actually using the correct path "/opt/traccar/data" worked wonders :-)
