### ISSUE TITLE
Reconnect DockerHub with GitHub

### ISSUE THREAD

**Issue by magna-z** [traccar/traccar-docker#35]
Hello @tananaev!
Please, reconnect "traccar" organization on DockerHub with GitHub for restore autobuilds after [data breach on hub.docker.com](https://thehackernews.com/2019/04/docker-hub-data-breach.html).

**Comment by tananaev** [comment]
Approved. Can we remove old `Docker Hub Registry` permission? Or is it still required?

**Comment by magna-z** [comment]
> Approved. Can we remove old `Docker Hub Registry` permission? Or is it still required?

You need to:
- clean all webhooks in this github repository
- relink accounts github&dockerhub in organization settings on DockerHub

Then i can fix autobuilds for traccar/traccar in DockerHub.

**Comment by tananaev** [comment]
Is there a way to do it without linking github account? No option with webhook?

**Comment by magna-z** [comment]
The first step is restore OAuth-link. When  wold be working link, I am restore repo settings include webhooks.

**Comment by tananaev** [comment]
Linked GitHub account to Docker.

**Comment by magna-z** [comment]
Hey @tananaev.
I`m researching cause why i not see organizations traccar in dockerhub. i`m create the team "DevOps" for fix this. Please set this team as Admins in this repository.

**Comment by tananaev** [comment]
Sorry, which team admin where?

**Comment by magna-z** [comment]
On [this page](https://github.com/traccar/traccar-docker/settings/collaboration) do "Add team", select "DevOps" and set permissions "Admin". Thanks!

**Comment by tananaev** [comment]
Why do you need an admin access? And why do you need a team?

**Comment by magna-z** [comment]
Fixed!!!
