### ISSUE TITLE
arquivo tracker-server

### ISSUE THREAD

**Issue by G-GOM** [traccar/traccar-docker#39]

**Comment by G-GOM** [comment]
ola...esse arquivo...tracker-server  vai aumentando o seu tamanho a cada segundo..teria um modo de q esse arquivo parasse de aumentar ?

**Comment by tananaev** [comment]
Use forum for questions.

**Comment by G-GOM** [comment]
# 44461 <https://www.traccar.org/forums/reply/44461/>

Em sex, 28 de jun de 2019 às 12:24, Anton Tananaev <notifications@github.com>
escreveu:
