### ISSUE TITLE
Raspberry pi ARM support

### ISSUE THREAD

**Issue by samabsalom** [traccar/traccar-docker#43]
Not sure if i'm missing something obvious or this image doesn't support the pi? some pointers as to how to get it going would very much appreciated. Thanks

**Comment by krasi-georgiev** [comment]
the new version of docker supports buildx command to build multi arch images and if the maintainers are willing to accept a PR I am willing to spend the time to add automated circle ci to docker hub for multi-arch images.

**Comment by tananaev** [comment]
@magna-z any thoughts?

**Comment by krasi-georgiev** [comment]
here is how an example config for this looks like

https://github.com/arribada/SMARTLoraTracker/blob/master/.circleci/config.yml

**Comment by magna-z** [comment]
I think Java app on ARM is very unique case.

At now build docker image do the "DockerHub Autobuild". Only with change CI to more functionally we can do multi-platform build with [docker buildx](https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images) or experimental [docker manifests](https://docs.docker.com/engine/reference/commandline/manifest/). We really need it?

**Comment by krasi-georgiev** [comment]
What do you mean by "unique"? I was thinking to run it on an RPI along with some other tools that will receive Lora packets and push them to traccar. It would be a really nice standalone device for boat tracking

**Comment by stskrp** [comment]
Any update on this? I'm also thinking to run traccar on RPI

**Comment by magna-z** [comment]
Unfortunately, I don’t have a time to migrate docker build process to another CI system.
At now you can build ARM version of image in personal repository or another solution.

When i have a time i will make multi-arch on GitHub Action. Very soon. It`s OK?
In use third-party CI (Circle or Travis) I do not see the point.

**Comment by krasi-georgiev** [comment]
yep GH actions is also a good choice.

**Comment by krasi-georgiev** [comment]
and it already exists for GH actions
https://github.com/marketplace/actions/docker-buildx

**Comment by sincze** [comment]
Created this to run Traccar on Raspberry Pi 4.
https://github.com/traccar/traccar-docker/issues/61

**Comment by magna-z** [comment]
Multi-platform docker images released for current version 4.11. [Details in README.md](https://github.com/traccar/traccar-docker#available-multi-platform-images)

**Comment by krasi-georgiev** [comment]
Big thanks, will try it soon!
