### ISSUE TITLE
Traccar auto-starts after reboot

### ISSUE THREAD

**Issue by NULUSIOS** [traccar/traccar-docker#44]
While this doesn't sound as a bug when first reading the subject, let me elaborate.

I use this container within an unRAID installation.
unRAID has the option to set which containers to auto-start and which to NOT auto-start.
For some reason, this container ignores the setting and auto-starts anyway.

**Comment by jangrewe** [comment]
While i'm not involved with Traccar, i suggest you check your command line how the Traccar container is started.
It can not start by itself, that's just technically impossible.
Either it was started with `--restart=always` and the Docker daemon sees that it was running before and starts it again, or whatever manages the containers on unRAID is ignoring that you don't want it to start.

Either way: this is not, and can not, be a problem with this image.
