### ISSUE TITLE
Include MQTT 

### ISSUE THREAD

**Issue by dersch81** [traccar/traccar-docker#57]
Hi, i'm wondering if you can include this MQTT project natively into your docker image? 

https://github.com/ivanfmartinez/ivanfm-traccar-mqtt

It would be very, very nice! :) 

Regards

**Comment by tananaev** [comment]
How is this related to docker?

**Comment by dersch81** [comment]
it need to be complied within the container, right?

**Comment by tananaev** [comment]
I don't think that's how it works. Our docker images use prebuilt binary packages of Traccar.

**Comment by magna-z** [comment]
This repository only for build docker images with original traccar application. Without external handlers.
If you want use traccar with mqtt, you can create issue in [ivanfmartinez/ivanfm-traccar-mqtt](https://github.com/ivanfmartinez/ivanfm-traccar-mqtt/issues) repository to create images when traccar will be worked with mqtt. Or create personal git & docker repository and build images based on [ivanfmartinez/ivanfm-traccar-mqtt](https://github.com/ivanfmartinez/ivanfm-traccar-mqtt) repo.
