### ISSUE TITLE
deploy trracr on pine64 running armbian buster

### ISSUE THREAD

**Issue by toblie** [traccar/traccar-docker#58]
hi, I tried to deploy traccar/traccar:latest  and also traccar/traccar:4.10-alpine to my pine64 running armbian buster.
But badly both versions wasn't running and the log shows this error: 

standard_init_linux.go:211: exec user process caused "exec format error"

Can anyone help me to get it working? I think it also caused of arm compatibility? Is there anything to do to get your multiarch version running?

Thanks so much!
Tobi

_Originally posted by @toblie in https://github.com/traccar/traccar-docker/pull/53#issuecomment-678041161_

**Comment by sincze** [comment]
Seems Pine64 and Raspberry are competition.
Created https://github.com/traccar/traccar-docker/issues/61 to run Traccar in a docker on my Raspberry Pi 4.

**Comment by toblie** [comment]
> Seems Pine64 and Raspberry are competition.
> Created #61 to run Traccar in a docker on my Raspberry Pi 4.

Thanks, but for me it's not working.
The log still shows an error: "Error: Unable to access jarfile tracker-server.jar"

**Comment by magna-z** [comment]
Multi-platform docker images released for current version 4.11. [Details in README.md](https://github.com/traccar/traccar-docker#available-multi-platform-images)
