### ISSUE TITLE
Deploy using docker compose throw error='Out of memory'

### ISSUE THREAD

**Issue by brojendev** [traccar/traccar-docker#59]
I try to deploy using docker compose file for traccar in a 1gb DO droplet, but its throwing following error
```
traccar-gps    | OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000eaaa0000, 357957632, 0) failed; error='Out of memory' (errno=12)
traccar-gps    | #
traccar-gps    | # There is insufficient memory for the Java Runtime Environment to continue.
traccar-gps    | # Native memory allocation (mmap) failed to map 357957632 bytes for committing reserved memory. 
```

**Comment by magna-z** [comment]
Default heap size in docker image is 512MB. It's worked fine on "1gb DO" if droplet used only for one traccar docker container.
Otherwise you can analyze free memory in `top` and `free -m` command output on droplet.
