### ISSUE TITLE
Unable to load library 'systemd'

### ISSUE THREAD

**Issue by jangrewe** [traccar/traccar-docker#60]
Hi, i've just discovered Traccar and love it!
I'm running the Docker image and everythings looks like it's working fine, but i get this error in the log:

```
WARN: No systemd support - Unable to load library 'systemd':
Error loading shared library libsystemd.so: No such file or directory
Error loading shared library libsystemd.so: No such file or directory
Native library (linux-x86-64/libsystemd.so) not found in resource path ([file:/opt/traccar/tracker-server.jar]) - UnsatisfiedLinkError (... < HealthCheckService:39 < Main:115 < *:148 < *:110)
```

I guess this is related to the Docker image (4.10-alpine) and also the server code, but i thought it's more appropriate here.

**Comment by tananaev** [comment]
Check this thread:

https://www.traccar.org/forums/topic/no-systemd-support-error-after-updating-to-traccar-410-on-docker/

**Comment by jangrewe** [comment]
Thanks, `<entry key='web.healthCheck'>false</entry>` did the trick!

**Comment by tananaev** [comment]
You can also safely ignore the warning.
