### ISSUE TITLE
MySQL Connection does not work

### ISSUE THREAD

**Issue by Civlo85** [traccar/traccar-docker#71]
Hello,

many thanks for your work regarding this docker setup! I am able to use traccar with all of my gps devices, thats fine. But I am still using the H2 database and I want to switch to MySQL.

I want to use the MySQL on the Host Machine, which is running Ubuntu 16.04 and MySQL at version 5.7.33-0ubuntu0.16.04.1. I already created a database for traccar and also an user as well as a password for it. I double checked all of it. The user has access to the database. I tried to change the traccar.xml as mentioned in your instructions. I deleted the 4 rows regarding the H2 database and addes the following rows instead:

`<entry key='database.driver'>com.mysql.cj.jdbc.Driver</entry>`
`<entry key='database.url'>jdbc:mysql://localhost:3306/db_traccar?serverTimezone=UTC&amp;useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>`
`<entry key='database.user'>traccar</entry>`
`<entry key='database.password'>myPassword</entry>`

But after running the docker I cannot connect to the web UI anymore. Looking into the logs revealed:

`2021-02-05 14:39:37  INFO: HikariPool-1 - Starting...`
`2021-02-05 14:41:12 ERROR: HikariPool-1 - Exception during pool initialization. - connect timed out - SocketTimeoutException (... < DataManager:126 < *:85 < Context:289 < Main:120 < ...)`
`2021-02-05 14:41:12 ERROR: Main method error - connect timed out - SocketTimeoutException (... < DataManager:126 < *:85 < Context:289 < Main:120 < ...)`

over and over without end. I also changed the "localhost" in the url to the ip address of the host. But it had no effect. I also changed the "bind-address" parameter to 0.0.0.0 in the mysql config file (and restarted mysql).

But it is still the same. It does not work with MySQL database on the host.

What can I do else?

**Comment by tananaev** [comment]
Are you sure MySQL is accepting connections? It seems like MySQL issue.

**Comment by Civlo85** [comment]
Thanks for your hint.

Indeed! I forgot to add a rule to my firewall. Sorry for that.

I added the rule with this command:

`sudo ufw allow 3306`

and restartetd the Firewall

`sudo ufw reload`

Then everything works as expected.
