### ISSUE TITLE
Traccar 4.13 doesn't support docker containers on Raspberry Pi 

### ISSUE THREAD

**Issue by Akretsch** [traccar/traccar-docker#76]
$ docker run  --platform linux/arm/v7 --restart always  --name traccar  --hostname traccar  -p 80:8082  -p 5000-5150:5000-5150  -p 5000-5150:5000-5150/udp  -v /var/docker/traccar/logs:/opt/traccar/logs:rw  -v /var/docker/traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro  traccar/traccar:4.1**3**
is refused with "docker: Error response from daemon: image with reference traccar/traccar:4.13 was found but does not match the specified platform: wanted linux/arm/v7, actual: linux/amd64"

But works for 
$ docker run  --platform linux/arm/v7 --restart always  --name traccar  --hostname traccar  -p 80:8082  -p 5000-5150:5000-5150  -p 5000-5150:5000-5150/udp  -v /var/docker/traccar/logs:/opt/traccar/logs:rw  -v /var/docker/traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro  traccar/traccar:4.1**2**

**Comment by meilon** [comment]
The tag [4.12](https://hub.docker.com/layers/traccar/traccar/4.12/images/sha256-5cfd8d14d332d56e2cfcd6afd207e3db2baa423769e7c5ba4f4a2ed08fe13eb2?context=explore) brought you the armv6 image, not the v7. For use with v7 use any of the ubuntu tags (ubuntu, 4-ubuntu or 4.13-ubuntu).

But yeah, the latest and version only tags should provide an image for every supported platform! Hopefully @magna-z updates the cookbook to support this.

**Comment by Akretsch** [comment]
$ docker run -d --restart always --name traccar --hostname traccar -p 80:8082 -p 5000-5150:5000-5150 -p 5000-5150:5000-5150/udp -v /var/docker/traccar/logs:/opt/traccar/logs:rw -v /var/docker/traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro traccar/traccar:ubuntu 

starts a container, but the traccar server isn't responsive, it refuses incoming connections:

$wget localhost
--2021-08-20 19:00:31--  http://localhost/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

$ docker logs traccar

reports a strange problem:

"OpenJDK Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes"

$ uname -a
Linux raspi3 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux

$ cat /etc/issue.net 
Raspbian GNU/Linux 10

falling back to "traccar/traccar:4.12" helps.

**Comment by Akretsch** [comment]
Rot cause was an incompatible libseccomp provided by my "Raspbian GNU/Linux 10".
Problem and Fix is described in https://docs.linuxserver.io/faq#libseccomp .
