### ISSUE TITLE
Abnormal RAM usage

### ISSUE THREAD

**Issue by StarkITA** [traccar/traccar-docker#80]
As referenced on the forums in [this post](https://www.traccar.org/forums/topic/confused-about-ram-usage/#post-66113) I have an issue with a docker-compose deployment.

RAM usage shoots up to 6GB with no load right away, spawning a huge number of java processes as you can see here: https://imgur.com/a/v4PZNrE

I did try using the docker run command on the project homepage, and still have a huge ram usage, and lots of java processes.

What could be going wrong? I did try both using the traccar/traccar-docker image and building from Dockerfile, to no change.

**Comment by grumpazoid** [comment]
Similar problems here. I am trying to run the image on an intel atom pc. CPU load and RAM maxes out upon launch and the host becomes unresponsive.

**Comment by SiriosDev** [comment]
in 2024 same problem
