### ISSUE TITLE
Database backup

### ISSUE THREAD

**Issue by 0xspade** [traccar/traccar-docker#86]
Every time I `stop` and `rm` my traccar docker, the database always resets, Is there a way how I prevent this?

**Comment by sincze** [comment]
Did you use a docker compose to store the H2 DB in a permanent location?? (So the DB is outside of the docker instead of in it).
Personally I store the DB in a separate MySQL container as described on the traccar website.

**Comment by jangrewe** [comment]
https://docs.docker.com/storage/volumes/
