### ISSUE TITLE
How to increase java RAM limit in existing Traccar docker container

### ISSUE THREAD

**Issue by alexsahka** [traccar/traccar-docker#95]
I can see this command in the Portainer interface:
java -Xms512m -Xmx512m -Djava.net.preferIPv4Stack=true -jar tracker-server.jar conf/traccar.xml

My question is how to increase the 512m command to 1Gig for example?

Thanks.

**Comment by tananaev** [comment]
@magna-z also should we increase default values? It seems like quite a few reports that the latest version of Traccar uses more memory.

**Comment by alexsahka** [comment]
Changing from
java -Xms512m -Xmx512m -Djava.net.preferIPv4Stack=true -jar tracker-server.jar conf/traccar.xml
to 
java,-Xms1024m,-Xmx1024m,-Djava.net.preferIPv4Stack=true
or
java,-Xms1g,-Xmx1g,-Djava.net.preferIPv4Stack=true

ending in error
